language: node_js
node_js:
  - "4.4"
script: gulp build
branches:
  only:
    - deploy
deploy:
  provider: heroku
  on: deploy
  skip_cleanup: true
  api_key:
    secure: "Yi2xYZTlq1pbwl5z7BWXPf3ROusRjuC9ckA7QfrxEgvTnOtdHkyIZN9hlKKW8niYc/vEMn9iQBs1gWEGXfSvVj1Ud2sZUMbtbvofKEynzu/S7RbuE6JN0HkkvA8A99p3706/cZRQyUVagIoHw+aDE8BaOj0yXK5+BSweFa+2jpxLh9vJtA6aOXwgeh8GlhcmZqBMOhNOAafN6zVged6T502wWDqkJ3cAHwz3mJo9NkHhd1uNXc4Ho7eTzuZzReRkDVcMKzjSZCpt+7VBLIW02pOoWZY7J5Rk3CjoY4f7P26BS2HwDPJSBoBa2UQZQd1Hv8mo7U+rrF27nuTSki7E/By552cqtP92Hw4pDxE+ppCr5VRIs9xYt2ldtdIfVH8mWf/zYVgmUtMN8TUNQ2H/TyzC7o7HqsnXWlfKoOWefUQO7C/YMtZAtv+lkKq0iVAcBRAQBnqjcdMpiNvQcMR9TgYnUV7m4iygC53jmnZPH8OINegHIka3W2HJ05r5Br4JbZt2vp2Ldd39RCewb1ZnrExVeWzJBuakJ3acZkfN7qo2I0wMlQus1UkKS4AFvGO/3MClm+ee7Ns55ttYmqcoJRC6NjDzqWncni7mHNnIwTqXOnWGs7ivnYR/0xPs5F1q7OLAQau3LtsOGkgP4UF09HgbAdyybGJkxOh27EnuSz8="
  app: testheroke
  run: npm start